apiVersion: v1
kind: Secret
metadata:
  name: index-template
  namespace: infra
type: Opaque
data:
  indextemplate.json: ICAgIHsKICAgICAgImluZGV4X3BhdHRlcm5zIjogWyI8PGluZGV4X3BhdHRlcm4+PiJdLAogICAgICAgICJzZXR0aW5ncyI6IHsKICAgICAgICAgICJudW1iZXJfb2Zfc2hhcmRzIjogIjIiLAogICAgICAgICAgIm51bWJlcl9vZl9yZXBsaWNhcyI6ICIxIiwKICAgICAgICAgICJpbmRleC5saWZlY3ljbGUubmFtZSI6ICI8PHJvbGxfbmFtZT4+IiwKICAgICAgICAgICJpbmRleC5saWZlY3ljbGUucm9sbG92ZXJfYWxpYXMiOiAiPDxyb2xsX2FsaWFzPj4iCiAgICAgICAgICAgIH0KICAgICAgICB9
